"""Shared Pydantic data contracts."""

from models.enums import (
    EvidenceSourceType,
    GraphEdgeType,
    GraphNodeType,
    HtmlNarrativeStatus,
    IntentSource,
    NarrativeSectionKind,
    OperationClass,
    QueryIntent,
    QueryStatus,
    RouterFallbackReason,
    SourceBias,
    Sufficiency,
)
from models.evaluation import (
    BenchmarkItem,
    BenchmarkResult,
    EvaluationRun,
    GroundTruth,
    JudgeVerdict,
)
from models.filing import CellSpan, FilingRef, FootnoteBlock, SectionBlock, TableBlock
from models.graph import GraphEdge, GraphManifest, GraphNode, GraphSnapshot
from models.graph_audit import (
    AuditEntry,
    FilingMaterializationResult,
    FilingMaterializationStatus,
    ReachabilityAuditReport,
)
from models.corpus import (
    BoundFilingEntry,
    CorpusDefinition,
    CorpusMaterializationJob,
    CorpusMember,
    CorpusTemporalScope,
    FilingBinding,
    FiscalPeriodLabel,
    IssuerSnapshotIndex,
    SnapshotScopeManifest,
)
from models.ingestion import (
    CacheEntry,
    CLIAskRequest,
    CLIAskResult,
    CLITestResult,
    FetchJob,
    FilingResolution,
    IssuerIdentifierInput,
    XBRLArtifact,
    XBRLArtifactManifest,
)
from models.parsing import ParsedDocument
from models.query import (
    AnswerPackage,
    EvidenceChunk,
    GraphVisit,
    IntentRouterTrace,
    MacroPlan,
    SectionCandidate,
    TemporalScope,
    TrajectoryRecord,
)

__all__ = [
    "EvidenceSourceType",
    "QueryIntent",
    "IntentSource",
    "SourceBias",
    "RouterFallbackReason",
    "NarrativeSectionKind",
    "HtmlNarrativeStatus",
    "GraphEdgeType",
    "GraphNodeType",
    "OperationClass",
    "QueryStatus",
    "Sufficiency",
    "FilingRef",
    "CellSpan",
    "SectionBlock",
    "TableBlock",
    "FootnoteBlock",
    "ParsedDocument",
    "GraphNode",
    "GraphEdge",
    "GraphManifest",
    "GraphSnapshot",
    "AuditEntry",
    "FilingMaterializationResult",
    "FilingMaterializationStatus",
    "ReachabilityAuditReport",
    "MacroPlan",
    "TemporalScope",
    "SectionCandidate",
    "EvidenceChunk",
    "IntentRouterTrace",
    "AnswerPackage",
    "GraphVisit",
    "TrajectoryRecord",
    "GroundTruth",
    "BenchmarkItem",
    "BenchmarkResult",
    "JudgeVerdict",
    "EvaluationRun",
    "FilingResolution",
    "XBRLArtifact",
    "XBRLArtifactManifest",
    "CacheEntry",
    "FetchJob",
    "IssuerIdentifierInput",
    "CLIAskRequest",
    "CLIAskResult",
    "CLITestResult",
    "CorpusDefinition",
    "CorpusMember",
    "CorpusMaterializationJob",
    "CorpusTemporalScope",
    "FilingBinding",
    "FiscalPeriodLabel",
    "BoundFilingEntry",
    "SnapshotScopeManifest",
    "IssuerSnapshotIndex",
]
